### ISSUE TITLE
`@@contract` protocol

### ISSUE THREAD

**Issue by igorkamyshev** [igorkamyshev/withease#10]
Farfetched has its abstractions for data validation — [_Validator_](https://farfetched.pages.dev/api/primitives/validator.html) and [_Conrtact_](https://farfetched.pages.dev/api/primitives/contract.html).

1. _Validator_ is quite specific for Farfetched because it can be [_sourced_](https://farfetched.pages.dev/api/primitives/sourced.html) and accepts object `{ params, result }`. Furthermore, there is no integration that provides some _Validators_ on top of external libraries.  So, in my opinion, _Validator_ should not be extracted from Farfetched for now.
2. _Contract_ is not specific for Farfetched at all. It just an object that takes type T1, checks that it conforms to type T2 and provides error messages after check. Moreover, we have a lot of integration (like `@farfetched/runtypes`, `@farfetched/zod`, etc.) that allow users to convert external contracts to _Contract_.

I purpose to add the protocol `@@contract` to With Ease. Any object with the following structure will be treated as _Contract_ and can be used anywhere across the ecosystem (Farfetched, effector-storage).

```ts
type ContractProtocol<T1, T1> = {
  '@@contract': {
    isData: (val: T1) => val is T2,
    getErrorMessages: (val: T1) => string[],
  }
}
```

Steps of adoption could be the following:
1. Add the protocol documentation to With Ease site
2. Support the protocol in Farfetched's integrations
3. Copy-paste Farfetched's integrations to With Ease repo
4. Deprecate integration under `@farfetched/*` and suggest users migrating to `@withease/*`
5. Support the protocol in `effector-storage`
6. Delete integrations from `@farfetched/*`

**Comment by igorkamyshev** [comment]
Sure.

1. Yes, it's for pleasing TypeScript 🤗
2. Why Error instance is better than a plain array? I am not against Error instance, but I do not see any advantage or disadvantage now.
3. Short names are nice, but they can lose some context. So, `is` is really charming, but “is what”? So, ugly names are better in case in my opinion.
4. _Contact_ is a runtime type-guard by original idea, so asynchronous type-guard is weird. I think, we have to rename the protocol to emphasize it. Something like `@@shapeValidator` or something like this.

However, discussion in the effector committee has led this protocol to nowhere. I assume, we have to pause its development until the next stage of discussion.

**Comment by victordidenko** [comment]
I think there is tiny and slippery difference between validation and contract, and it should be stated more sound.
I personally don't understand the difference :)

What is "type-guard"? What is "type"? `string` is obviously a type, but what about template literal types, like
<img width="278" alt="image" src="https://user-images.githubusercontent.com/15016227/228624899-4234bdca-016b-4973-9009-6ccc0aaf05b4.png">
What about string length, which is _very hard_ to express with TypeScript types? What about file of exact mime-type, which you can check only by reading N first bytes of file?

I feel there might be a case for asynchronous check. There are API, which simply doesn't not exist in sync version, for example `SubtleCrypto`. What if you want to verify signature in contract?

About names, `isData` is not much better, than `is`, in my opinion. "is data? of course this _is_ data, you silly, is data _what_?"

---

From `effector-storage` point of view, I think it would be great, if contract (aka validation imo) would be just a single function, which I could put into effect as a handler internally. If data has passed — effect will finish with `.done`. If validation is failed — effect will finish with `.fail`. I could get an error from `.failData`, whatever it is. Validation could be sync or async, doesn't matter. Sync validation could throw an exception — effect will handle it.

**Comment by igorkamyshev** [comment]
https://withease.pages.dev/protocols/contract.html
