### ISSUE TITLE
Bug(Media query): matched events not fired after setup

### ISSUE THREAD

**Issue by domosedov** [igorkamyshev/withease#43]
## Description
Matched event not fired after setup, works only after window width changes

## Repo
[Stackblitz](https://stackblitz.com/edit/effector-react-ts6dco?file=src%2Fmodel.ts,src%2Fapplication.tsx)

## Expected behavior:
Matched event fired after setup

**Comment by igorkamyshev** [comment]
Thanks for report, fixed in @withease/web-api@0.4.4
